CREATE TABLE IF NOT EXISTS cpf_restituicoes (id SERIAL PRIMARY KEY, cpf TEXT UNIQUE NOT NULL, valor NUMERIC(10,2) NOT NULL);
CREATE TABLE IF NOT EXISTS visitantes (id SERIAL PRIMARY KEY, cpf TEXT UNIQUE, nome TEXT, telefone TEXT, email TEXT, data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS paginas_visitadas (id SERIAL PRIMARY KEY, visitante_id INTEGER REFERENCES visitantes(id), pagina TEXT NOT NULL, data_acesso TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
